# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: gnode-api.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-api
            port:
              number: 80